# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Act < Formula
  desc "AWS Connect TUI - connect to EC2 instances via Session Manager"
  homepage "https://github.com/brunodasilvalenga/act"
  version "0.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/brunodasilvalenga/act/releases/download/v0.0.9/act_0.0.9_darwin_amd64.tar.gz"
      sha256 "3a69a2914d94955b47c2db43b5b4d0e2a51f4a47a01e131ee6f756360d7d208d"

      define_method(:install) do
        bin.install "act"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/brunodasilvalenga/act/releases/download/v0.0.9/act_0.0.9_darwin_arm64.tar.gz"
      sha256 "888329a186db9f1b93f301098919918921b255168848818807dfa7de9af85509"

      define_method(:install) do
        bin.install "act"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/brunodasilvalenga/act/releases/download/v0.0.9/act_0.0.9_linux_amd64.tar.gz"
      sha256 "efe6653f86e4da9bca2b238aec34add3c34341ed78e94c2343d3a78b085fecf0"
      define_method(:install) do
        bin.install "act"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brunodasilvalenga/act/releases/download/v0.0.9/act_0.0.9_linux_arm64.tar.gz"
      sha256 "4e4b23ae938f5582994a727e74789bf8241d3e249a127f86c92ea9f9fbdf6cb2"
      define_method(:install) do
        bin.install "act"
      end
    end
  end
end
